# DataSource PostgreSQL - dev (local)
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_plateform_db
spring.datasource.username=postgres
spring.datasource.password=Admin235
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA - dev
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging - dev
logging.level.com.ai_plateform_api=DEBUG
logging.level.org.flywaydb=DEBUG

# Anthropic API
anthropic.api.key=YOUR_API_KEY_HERE
anthropic.model=claude-sonnet-4-6